//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResultStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string iInputFileDefaultColumnLength {
            get {
                return ResourceManager.GetString("iInputFileDefaultColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string sAxisX {
            get {
                return ResourceManager.GetString("sAxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string sAxisY {
            get {
                return ResourceManager.GetString("sAxisY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string sAxisZ {
            get {
                return ResourceManager.GetString("sAxisZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Trying to populate chart that is null. .
        /// </summary>
        internal static string sChartNotAssigned {
            get {
                return ResourceManager.GetString("sChartNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No data found. .
        /// </summary>
        internal static string sErrNoData {
            get {
                return ResourceManager.GetString("sErrNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector array must contain exactly three components..
        /// </summary>
        internal static string sErrTextInvalidVector {
            get {
                return ResourceManager.GetString("sErrTextInvalidVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\Library\\Input.
        /// </summary>
        internal static string sIntialDirectoryPath {
            get {
                return ResourceManager.GetString("sIntialDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string sMeasurementText {
            get {
                return ResourceManager.GetString("sMeasurementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part ID.
        /// </summary>
        internal static string sPartID {
            get {
                return ResourceManager.GetString("sPartID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average calculated for this axis is #VALUE#..
        /// </summary>
        internal static string sTextAverage {
            get {
                return ResourceManager.GetString("sTextAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value found for this axis is #VALUE# against Part ID: #PARTID#.
        /// </summary>
        internal static string sTextMaximum {
            get {
                return ResourceManager.GetString("sTextMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value found for this axis is #VALUE# against Part ID: #PARTID#.
        /// </summary>
        internal static string sTextMinimum {
            get {
                return ResourceManager.GetString("sTextMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation in values is calculated to be #VALUE#.
        /// </summary>
        internal static string sTextVariation {
            get {
                return ResourceManager.GetString("sTextVariation", resourceCulture);
            }
        }
    }
}
