//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResultStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string iInputFileDefaultColumnLength {
            get {
                return ResourceManager.GetString("iInputFileDefaultColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Statistic View Class initialization didnot work correctly. AxisStatistics not initialized.
        /// </summary>
        internal static string sAxisStatLoadError {
            get {
                return ResourceManager.GetString("sAxisStatLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string sAxisX {
            get {
                return ResourceManager.GetString("sAxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string sAxisY {
            get {
                return ResourceManager.GetString("sAxisY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string sAxisZ {
            get {
                return ResourceManager.GetString("sAxisZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Trying to populate chart that is null. .
        /// </summary>
        internal static string sChartNotAssigned {
            get {
                return ResourceManager.GetString("sChartNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open log to see details..
        /// </summary>
        internal static string sCheckLog {
            get {
                return ResourceManager.GetString("sCheckLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value.
        /// </summary>
        internal static string sEnterValueText {
            get {
                return ResourceManager.GetString("sEnterValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No data found. .
        /// </summary>
        internal static string sErrNoData {
            get {
                return ResourceManager.GetString("sErrNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector array must contain exactly three components..
        /// </summary>
        internal static string sErrTextInvalidVector {
            get {
                return ResourceManager.GetString("sErrTextInvalidVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part(s) out of range:.
        /// </summary>
        internal static string sHeaderOutOfToleranceParts {
            get {
                return ResourceManager.GetString("sHeaderOutOfToleranceParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\\Library\\Input.
        /// </summary>
        internal static string sIntialDirectoryPath {
            get {
                return ResourceManager.GetString("sIntialDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part IDs with all axis values outside the tolerance range are highlighted in Red..
        /// </summary>
        internal static string sLabelTextOutlierParts {
            get {
                return ResourceManager.GetString("sLabelTextOutlierParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends in axis values as PartsID increases:.
        /// </summary>
        internal static string sLabelTextTrends {
            get {
                return ResourceManager.GetString("sLabelTextTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        internal static string sMeasurementText {
            get {
                return ResourceManager.GetString("sMeasurementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Parts lies outside the calculated tolerance range..
        /// </summary>
        internal static string sNoneText {
            get {
                return ResourceManager.GetString("sNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part ID.
        /// </summary>
        internal static string sPartID {
            get {
                return ResourceManager.GetString("sPartID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outliers: (PartID (X,Y,Z).
        /// </summary>
        internal static string sTextOutlierPart {
            get {
                return ResourceManager.GetString("sTextOutlierPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis outside their respective tolerance are highlighted in Pink..
        /// </summary>
        internal static string sTextTolerenceHighlightMessage {
            get {
                return ResourceManager.GetString("sTextTolerenceHighlightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter percentage to calculate tolerance range. For example, if variation is 20 and mean is 50, and tolerance input is 10%, then tolerance range will be between 48-52.  .
        /// </summary>
        internal static string sToleranceExplaination {
            get {
                return ResourceManager.GetString("sToleranceExplaination", resourceCulture);
            }
        }
    }
}
